language: generic
dist: trusty
os: linux
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - llvm-4.0
      - llvm-4.0-dev
      - clang-4.0
matrix:
  include:
    - os: osx
      env:
        - CXX=clang++ PATH=/usr/local/opt/llvm/bin:$PATH LLVM_DIR=/usr/local/opt/llvm LDFLAGS:=-L/usr/local/opt/llvm/lib CPPFLAGS=-I/usr/local/opt/llvm/include
        - CONFIG_ARGS="-DCMAKE_BUILD_TYPE:STRING=Debug"
      install: brew install llvm
      cache:
        directories: ~/Library/Caches/Homebrew/
    - os: osx
      env:
        - CXX=clang++ PATH=/usr/local/opt/llvm/bin:$PATH LLVM_DIR=/usr/local/opt/llvm LDFLAGS:=-L/usr/local/opt/llvm/lib CPPFLAGS=-I/usr/local/opt/llvm/include
        - CONFIG_ARGS=
      install: brew install llvm
      cache:
        directories: ~/Library/Caches/Homebrew/
env:
  global:
    - CC=clang-4.0 CXX=clang++-4.0
    - PATH=$TRAVIS_BUILD_DIR/cmake-3.8.1-Linux-x86_64/bin:$PATH
    - LLVM_DIR=/usr/lib/llvm-4.0
  matrix:
    - CONFIG_ARGS="-DCMAKE_BUILD_TYPE:STRING=Debug"
    - CONFIG_ARGS=
install: curl https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz | tar xz
script: mkdir build && pushd build && cmake $CONFIG_ARGS $TRAVIS_BUILD_DIR && make -j4 && popd
